import React, { useMemo, useState } from 'react';
import { FlatList, Modal, Pressable, SafeAreaView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { Brand, brands, CatalogProduct, catalogCheckedAt, searchCatalog } from './catalog';
import { s } from './styles';

export function CatalogScreen({ initialQuery, onClose }: { initialQuery: string; onClose: () => void }) {
  const [query, setQuery] = useState(initialQuery);
  const [brand, setBrand] = useState<Brand>('Все марки');
  const [selected, setSelected] = useState<CatalogProduct | null>(null);
  const results = useMemo(() => searchCatalog(query, brand), [query,brand]);
  return <View style={c.root}>
    <View style={c.top}><Pressable accessibilityRole="button" onPress={onClose} style={c.back}><Text style={c.backText}>← Миксы</Text></Pressable><Text style={s.meta}>18+ · бесплатно</Text></View>
    <Text style={c.title}>Палитра вкусов</Text>
    <Text style={c.subtitle}>Каталоги популярных марок · {results.length} позиций</Text>
    <TextInput accessibilityLabel="Поиск вкуса или ноты" autoCorrect={false} value={query} onChangeText={setQuery} placeholder="Вкус или название" placeholderTextColor="#8D9889" style={c.search} />
    <View style={c.chips}>{brands.map(item => <Pressable key={item} accessibilityRole="button" accessibilityState={{selected:brand===item}} onPress={() => setBrand(item)} style={[c.chip,brand===item && c.chipActive]}><Text style={[c.chipText,brand===item && c.chipTextActive]}>{item}</Text></Pressable>)}</View>
    <FlatList data={results} keyboardShouldPersistTaps="handled" keyExtractor={item => item.id} contentContainerStyle={c.list} ListEmptyComponent={<Text style={c.empty}>Не нашли совпадений. Попробуй другую ноту или переключи марку.</Text>} renderItem={({item}) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.brand}, ${item.name}`} onPress={() => setSelected(item)} style={c.item}><View style={{flex:1}}><Text style={c.brand}>{item.brand}{item.tng ? ' · TNG' : ''}</Text><Text style={c.name}>{item.name}</Text></View><Text style={c.arrow}>↗</Text></Pressable>} ListFooterComponent={<Text style={c.footer}>Каталог сверен {catalogCheckedAt}. Метка TNG означает марку, связанную с ассортиментом или проектами сети по открытым материалам TNG. Остатки и набор марок отличаются по филиалам — наличие уточняй у мастера.</Text>} />
    <Modal visible={selected!==null} animationType="slide" onRequestClose={() => setSelected(null)}><SafeAreaView style={s.recipeSafe}><View style={c.detail}><Pressable accessibilityRole="button" onPress={() => setSelected(null)}><Text style={c.close}>Закрыть ×</Text></Pressable><Text style={c.detailBrand}>{selected?.brand}</Text><Text style={c.detailName}>{selected?.name}</Text><Text style={c.detailHint}>Покажи название мастеру и уточни, есть ли этот вкус в заведении. Одна позиция бренда может сочетать несколько вкусовых нот.</Text><Pressable accessibilityRole="button" style={s.shareButton} onPress={() => selected && Share.share({message:`${selected.brand} — ${selected.name}\nЕсть ли этот вкус в наличии?`})}><Text style={s.whiteButtonText}>Поделиться названием</Text></Pressable></View></SafeAreaView></Modal>
  </View>;
}

const c = StyleSheet.create({root:{flex:1,backgroundColor:'#141714',paddingTop:24},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:24},back:{paddingVertical:12},backText:{fontSize:17,color:'#D5F589',fontWeight:'600'},title:{fontSize:34,fontWeight:'700',color:'#F4F5EF',marginTop:26,marginHorizontal:24},subtitle:{fontSize:15,color:'#A7AFA3',marginHorizontal:24,marginTop:8},search:{marginHorizontal:24,marginTop:23,paddingHorizontal:17,height:55,borderRadius:15,backgroundColor:'#252B24',fontSize:16,color:'#F4F5EF'},chips:{flexDirection:'row',gap:8,flexWrap:'wrap',paddingHorizontal:24,marginTop:15,marginBottom:10},chip:{paddingHorizontal:14,paddingVertical:12,borderRadius:20,backgroundColor:'#252B24'},chipActive:{backgroundColor:'#D5F589'},chipText:{fontSize:14,color:'#CDD2C8'},chipTextActive:{color:'#1E2916',fontWeight:'700'},list:{paddingHorizontal:24,paddingBottom:45},item:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:17,borderBottomWidth:1,borderBottomColor:'#2A3228'},brand:{fontSize:11,letterSpacing:1.4,fontWeight:'700',color:'#D5F589'},name:{fontSize:17,lineHeight:24,color:'#F4F5EF',marginTop:5},arrow:{fontSize:23,color:'#A7AFA3'},empty:{fontSize:16,lineHeight:24,color:'#A7AFA3',marginTop:25},footer:{fontSize:13,lineHeight:20,color:'#A7AFA3',marginTop:30},detail:{padding:28,flex:1},close:{alignSelf:'flex-end',fontSize:16,color:'#374A2D',paddingVertical:12},detailBrand:{fontSize:14,fontWeight:'700',letterSpacing:1.5,color:'#526647',marginTop:65},detailName:{fontSize:36,fontWeight:'700',lineHeight:44,color:'#202C1A',marginTop:16},detailHint:{fontSize:17,lineHeight:26,color:'#52604A',marginTop:30}});
