import React, { useMemo, useState } from 'react';
import { FlatList, Modal, Pressable, SafeAreaView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { Brand, brands, CatalogProduct, catalogCheckedAt, searchCatalog } from './catalog';
import { s } from './styles';

export function CatalogScreen({ initialQuery, onClose }: { initialQuery: string; onClose: () => void }) {
  const [query, setQuery] = useState(initialQuery);
  const [brand, setBrand] = useState<Brand>('Все марки');
  const [selected, setSelected] = useState<CatalogProduct | null>(null);
  const results = useMemo(() => searchCatalog(query, brand), [query,brand]);
  return <View style={c.root}>
    <View style={c.top}><Pressable accessibilityRole="button" onPress={onClose} style={c.back}><Text style={c.backText}>←  Назад</Text></Pressable><Text style={s.meta}>{results.length} ИЗ 530</Text></View>
    <Text style={c.eyebrow}>БИБЛИОТЕКА ВКУСОВ</Text><Text style={c.title}>Палитра</Text>
    <Text style={c.subtitle}>Найди конкретный продукт или исследуй ассортимент по маркам.</Text>
    <View style={c.searchWrap}><Text style={c.searchIcon}>⌕</Text><TextInput accessibilityLabel="Поиск вкуса или ноты" autoCorrect={false} value={query} onChangeText={setQuery} placeholder="Вкус, нота или марка" placeholderTextColor="#747C76" style={c.search} />{query.length > 0 && <Pressable onPress={() => setQuery('')}><Text style={c.clear}>×</Text></Pressable>}</View>
    <View style={c.chips}>{brands.map(item => <Pressable key={item} accessibilityRole="button" accessibilityState={{selected:brand===item}} onPress={() => setBrand(item)} style={[c.chip,brand===item && c.chipActive]}><Text style={[c.chipText,brand===item && c.chipTextActive]}>{item}</Text></Pressable>)}</View>
    <FlatList data={results} keyboardShouldPersistTaps="handled" keyExtractor={item => item.id} contentContainerStyle={c.list} ListEmptyComponent={<Text style={c.empty}>Не нашли совпадений. Попробуй другую ноту или переключи марку.</Text>} renderItem={({item}) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.brand}, ${item.name}`} onPress={() => setSelected(item)} style={c.item}><View style={{flex:1}}><Text style={c.brand}>{item.brand}{item.tng ? ' · TNG' : ''}</Text><Text style={c.name}>{item.name}</Text></View><Text style={c.arrow}>↗</Text></Pressable>} ListFooterComponent={<Text style={c.footer}>Каталог сверен {catalogCheckedAt}. Метка TNG означает марку, связанную с ассортиментом или проектами сети по открытым материалам TNG. Остатки и набор марок отличаются по филиалам — наличие уточняй у мастера.</Text>} />
    <Modal visible={selected!==null} animationType="slide" onRequestClose={() => setSelected(null)}><SafeAreaView style={s.recipeSafe}><View style={c.detail}><Pressable accessibilityRole="button" onPress={() => setSelected(null)}><Text style={c.close}>Закрыть ×</Text></Pressable><Text style={c.detailBrand}>{selected?.brand}</Text><Text style={c.detailName}>{selected?.name}</Text><Text style={c.detailHint}>Покажи название мастеру и уточни, есть ли этот вкус в заведении. Одна позиция бренда может сочетать несколько вкусовых нот.</Text><Pressable accessibilityRole="button" style={s.shareButton} onPress={() => selected && Share.share({message:`${selected.brand} — ${selected.name}\nЕсть ли этот вкус в наличии?`})}><Text style={s.whiteButtonText}>Поделиться названием</Text></Pressable></View></SafeAreaView></Modal>
  </View>;
}

const c = StyleSheet.create({root:{flex:1,backgroundColor:'#0D0F0E',paddingTop:18},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20},back:{paddingVertical:12,paddingRight:12},backText:{fontSize:15,color:'#D7F49A',fontWeight:'600'},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:2,color:'#8B967F',marginTop:30,marginHorizontal:20},title:{fontSize:46,fontWeight:'600',letterSpacing:-1.7,color:'#F2F0E9',marginTop:8,marginHorizontal:20},subtitle:{fontSize:15,lineHeight:23,color:'#89918B',marginHorizontal:20,marginTop:10,maxWidth:390},searchWrap:{height:56,marginHorizontal:20,marginTop:24,paddingHorizontal:16,borderRadius:18,backgroundColor:'#181B19',borderWidth:1,borderColor:'#292E2A',flexDirection:'row',alignItems:'center'},searchIcon:{fontSize:24,color:'#8B938D',marginRight:10},search:{flex:1,height:54,fontSize:16,color:'#F2F0E9'},clear:{fontSize:24,color:'#929A94',paddingLeft:10},chips:{flexDirection:'row',gap:7,flexWrap:'wrap',paddingHorizontal:20,marginTop:14,marginBottom:12},chip:{paddingHorizontal:13,paddingVertical:10,borderRadius:18,backgroundColor:'#181B19',borderWidth:1,borderColor:'#292E2A'},chipActive:{backgroundColor:'#D7F49A',borderColor:'#D7F49A'},chipText:{fontSize:13,color:'#B7BDB8'},chipTextActive:{color:'#1E2916',fontWeight:'700'},list:{paddingHorizontal:20,paddingBottom:45},item:{flexDirection:'row',alignItems:'center',gap:12,padding:16,marginBottom:8,borderRadius:17,backgroundColor:'#151817',borderWidth:1,borderColor:'#242925'},brand:{fontSize:10,letterSpacing:1.5,fontWeight:'700',color:'#AFC77C'},name:{fontSize:16,lineHeight:23,color:'#F2F0E9',marginTop:6},arrow:{fontSize:20,color:'#737B75'},empty:{fontSize:16,lineHeight:24,color:'#A7AFA3',marginTop:25},footer:{fontSize:12,lineHeight:19,color:'#737B75',marginTop:26},detail:{padding:28,flex:1},close:{alignSelf:'flex-end',fontSize:16,color:'#374A2D',paddingVertical:12},detailBrand:{fontSize:12,fontWeight:'700',letterSpacing:1.8,color:'#526647',marginTop:65},detailName:{fontSize:40,fontWeight:'600',letterSpacing:-1,lineHeight:47,color:'#202C1A',marginTop:16},detailHint:{fontSize:17,lineHeight:27,color:'#52604A',marginTop:30}});
