import { Platform, StatusBar, StyleSheet } from 'react-native';

const ink = '#F8F0E8';
const muted = '#A69BAA';
const line = '#302638';
const surface = '#17111D';
const raised = '#201727';
const coral = '#FF775C';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0D0911', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  appBody: { flex: 1 },
  page: { width: '100%', maxWidth: 680, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 132 },
  pressed: { opacity: .78 },

  topbar: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 34 },
  logoLockup: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  logoTile: { width: 38, height: 38, borderRadius: 13, backgroundColor: coral, overflow: 'hidden' },
  logoCutout: { position: 'absolute', width: 23, height: 23, borderRadius: 12, backgroundColor: '#0D0911', left: -8, top: 7 },
  logoDot: { position: 'absolute', width: 7, height: 7, borderRadius: 4, backgroundColor: '#271423', right: 8, top: 8 },
  logo: { fontSize: 17, lineHeight: 19, fontWeight: '900', letterSpacing: 1.5, color: ink },
  logoCaption: { marginTop: 2, fontSize: 7, fontWeight: '800', letterSpacing: 2.3, color: '#756A79' },
  topbarButton: { minWidth: 62, height: 42, borderRadius: 21, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: surface, borderWidth: 1, borderColor: line },
  topbarHeart: { color: coral, fontSize: 20 },
  topbarCount: { color: ink, fontSize: 13, fontWeight: '800' },
  collectionCountBadge: { minWidth: 42, height: 42, paddingHorizontal: 11, alignItems: 'center', justifyContent: 'center', borderRadius: 21, backgroundColor: raised, borderWidth: 1, borderColor: '#3A2D42' },
  collectionCountNumber: { color: '#C7A6FF', fontWeight: '900', fontSize: 14 },

  updateStrip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12, borderRadius: 15, backgroundColor: '#211827', marginBottom: 25, borderWidth: 1, borderColor: '#3A2940' },
  updatePulse: { width: 7, height: 7, borderRadius: 4, backgroundColor: coral, marginRight: 9 },
  updateStripText: { flex: 1, color: '#D8CADC', fontSize: 12, fontWeight: '600' },
  updateStripLink: { color: coral, fontSize: 12, fontWeight: '800' },

  heroBlock: { marginBottom: 39 },
  heroKicker: { color: coral, fontSize: 10, fontWeight: '900', letterSpacing: 2.2 },
  heroTitle: { color: ink, fontSize: 58, lineHeight: 59, fontWeight: '500', letterSpacing: -3, marginTop: 14 },
  heroText: { maxWidth: 460, color: muted, fontSize: 16, lineHeight: 24, marginTop: 18 },

  stepHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  stepNumber: { width: 27, color: '#655A69', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  stepRule: { width: 25, height: 1, backgroundColor: '#493B50', marginRight: 10 },
  stepTitle: { color: '#9A8E9E', fontSize: 10, fontWeight: '900', letterSpacing: 2 },
  profileRail: { gap: 10, paddingRight: 20, paddingBottom: 34 },
  profileCard: { width: 124, minHeight: 142, padding: 15, borderRadius: 22, backgroundColor: surface, borderWidth: 1, borderColor: line },
  profileIcon: { color: coral, fontSize: 25, lineHeight: 30, marginBottom: 23 },
  profileIconActive: { color: '#1B0F13' },
  profileLabel: { color: ink, fontSize: 16, fontWeight: '800' },
  profileLabelActive: { color: '#241316' },
  profileCaption: { color: '#807583', fontSize: 11, lineHeight: 15, marginTop: 6 },
  profileCaptionActive: { color: '#543129' },

  labCard: { position: 'relative', overflow: 'hidden', padding: 19, borderRadius: 28, backgroundColor: raised, borderWidth: 1, borderColor: '#3A2D42', marginBottom: 37 },
  labDecorOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, backgroundColor: '#A56BFF', opacity: .055, right: -60, top: -80 },
  labDecorTwo: { position: 'absolute', width: 120, height: 120, borderRadius: 60, backgroundColor: coral, opacity: .055, left: -50, bottom: 30 },
  labTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  labEyebrow: { color: coral, fontSize: 9, fontWeight: '900', letterSpacing: 2 },
  labTitle: { color: ink, fontSize: 24, fontWeight: '700', letterSpacing: -.7, marginTop: 5 },
  labBadge: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12, backgroundColor: '#2E2136', borderWidth: 1, borderColor: '#45344D' },
  labBadgeText: { color: '#C7A6FF', fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
  flavourStack: { minHeight: 109, justifyContent: 'center', alignItems: 'flex-start', gap: 5, marginTop: 17, padding: 13, borderRadius: 19, backgroundColor: '#120D17' },
  flavourLayer: { height: 25, borderRadius: 9, justifyContent: 'center', paddingHorizontal: 11 },
  flavourLayerText: { color: '#271517', fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },
  flavourLayerTextDark: { color: '#5C4640' },
  labControl: { minHeight: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#3A2D42' },
  controlLabel: { color: '#E9DDEB', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  controlHint: { color: '#7E7182', fontSize: 11, marginTop: 5 },
  segment: { flexDirection: 'row', padding: 4, borderRadius: 15, backgroundColor: '#110D15' },
  segmentButton: { width: 39, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 11 },
  segmentButtonActive: { backgroundColor: '#F6EAE3' },
  segmentText: { color: '#8D7F91', fontSize: 14, fontWeight: '800' },
  segmentTextActive: { color: '#241820' },
  switchRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingVertical: 13 },
  switchTrack: { width: 50, height: 29, borderRadius: 15, padding: 3, justifyContent: 'center', backgroundColor: '#3A2C40' },
  switchTrackActive: { backgroundColor: coral },
  switchThumb: { width: 23, height: 23, borderRadius: 12, backgroundColor: '#A698AA' },
  switchThumbActive: { backgroundColor: '#241216', marginLeft: 21 },
  generateButton: { minHeight: 58, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, borderRadius: 18, backgroundColor: coral, marginTop: 7 },
  generateSpark: { color: '#271416', fontSize: 19, marginRight: 10 },
  generateText: { color: '#271416', fontSize: 16, fontWeight: '900' },
  generateArrow: { color: '#271416', fontSize: 23, marginLeft: 'auto' },

  resultSection: { marginBottom: 42 },
  resultCard: { position: 'relative', overflow: 'hidden', borderRadius: 31, padding: 21, backgroundColor: '#F4E9E1', borderWidth: 1 },
  resultHalo: { position: 'absolute', width: 270, height: 270, borderRadius: 135, opacity: .18, top: -150, right: -90 },
  resultTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  resultProfile: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 16 },
  resultDot: { width: 7, height: 7, borderRadius: 4 },
  resultProfileText: { fontSize: 11, fontWeight: '900', letterSpacing: .4 },
  resultFavorite: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E7DBD4' },
  resultFavoriteActive: { backgroundColor: '#271820' },
  resultFavoriteText: { color: '#6A5962', fontSize: 23 },
  resultFavoriteTextActive: { color: coral },
  resultTitle: { color: '#261B21', fontSize: 37, lineHeight: 42, fontWeight: '700', letterSpacing: -1.5, marginTop: 26 },
  resultDescription: { color: '#74636B', fontSize: 15, lineHeight: 23, marginTop: 11 },
  recipeFormula: { marginTop: 27, gap: 17 },
  formulaRow: { gap: 8 },
  formulaTop: { flexDirection: 'row', alignItems: 'baseline', gap: 10 },
  formulaNameWrap: { flex: 1, flexDirection: 'row', alignItems: 'baseline', gap: 9 },
  formulaIndex: { width: 19, color: '#9B898F', fontSize: 9, fontWeight: '800' },
  formulaName: { flex: 1, color: '#34262D', fontSize: 15, lineHeight: 20, fontWeight: '700' },
  formulaPercent: { color: '#261B21', fontSize: 22, fontWeight: '900' },
  formulaPercentMark: { fontSize: 11, color: '#88767E' },
  formulaTrack: { height: 5, marginLeft: 28, borderRadius: 3, backgroundColor: '#D9CCC6', overflow: 'hidden' },
  formulaFill: { height: 5, borderRadius: 3 },
  authorChip: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 14, borderRadius: 17, backgroundColor: '#E4D9D2', marginTop: 24 },
  authorChipIcon: { width: 30, height: 30, borderRadius: 15, textAlign: 'center', textAlignVertical: 'center', color: '#F4E9E1', backgroundColor: '#2B1C24', fontSize: 14 },
  authorChipCopy: { flex: 1 },
  authorChipLabel: { color: '#8B707B', fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },
  authorChipName: { color: '#34262D', fontSize: 13, fontWeight: '800', marginTop: 4 },
  authorChipArrow: { color: '#594650', fontSize: 19 },
  masterButton: { minHeight: 58, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, borderRadius: 18, backgroundColor: '#2B1C24', marginTop: 23 },
  masterButtonText: { color: '#FFF8F1', fontSize: 15, fontWeight: '800' },
  masterButtonArrow: { color: coral, fontSize: 21, marginLeft: 'auto' },

  editorialHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 15, marginBottom: 16 },
  editorialKicker: { color: '#746A78', fontSize: 9, fontWeight: '900', letterSpacing: 1.7 },
  editorialTitle: { color: ink, fontSize: 24, fontWeight: '700', letterSpacing: -.7, marginTop: 6 },
  editorialLink: { color: coral, fontSize: 12, fontWeight: '800', paddingVertical: 7 },
  recommendationRail: { gap: 11, paddingRight: 20 },
  recommendationCard: { width: 207, minHeight: 258, padding: 13, borderRadius: 23, backgroundColor: surface, borderWidth: 1, borderColor: line },
  recommendationVisual: { height: 104, borderRadius: 16, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  recommendationDisc: { width: 58, height: 58, borderRadius: 29, borderWidth: 8, alignItems: 'center', justifyContent: 'center', opacity: .9 },
  recommendationDiscCore: { width: 13, height: 13, borderRadius: 7 },
  recommendationNumber: { position: 'absolute', right: 10, top: 9, fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  recommendationProfile: { color: '#7C6F80', fontSize: 8, fontWeight: '900', letterSpacing: 1.5, marginTop: 14 },
  recommendationTitle: { color: ink, fontSize: 17, lineHeight: 21, fontWeight: '800', marginTop: 7 },
  recommendationMeta: { color: '#8B7F8E', fontSize: 10, marginTop: 'auto', paddingTop: 13 },
  legal: { color: '#685E6C', fontSize: 11, lineHeight: 17, marginTop: 28 },

  screenKicker: { color: coral, fontSize: 10, fontWeight: '900', letterSpacing: 2.1 },
  screenTitle: { color: ink, fontSize: 50, lineHeight: 56, fontWeight: '600', letterSpacing: -2.3, marginTop: 10 },
  screenSubtitle: { maxWidth: 440, color: muted, fontSize: 15, lineHeight: 23, marginTop: 13 },
  collectionTabs: { flexDirection: 'row', padding: 5, borderRadius: 18, backgroundColor: surface, borderWidth: 1, borderColor: line, marginTop: 28, marginBottom: 19 },
  collectionTab: { flex: 1, minHeight: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 13 },
  collectionTabActive: { backgroundColor: '#F4E9E1' },
  collectionTabText: { color: '#8E8292', fontSize: 12, fontWeight: '800' },
  collectionTabTextActive: { color: '#281B22' },
  collectionList: { gap: 9 },
  recipeListCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 22, backgroundColor: surface, borderWidth: 1, borderColor: line, overflow: 'hidden' },
  recipeListMain: { flex: 1, minHeight: 104, flexDirection: 'row', alignItems: 'center', gap: 13, padding: 11 },
  recipeListArt: { width: 71, height: 78, borderRadius: 17, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  recipeListOrb: { width: 34, height: 34, borderRadius: 17, opacity: .78 },
  recipeListArtText: { position: 'absolute', right: 7, top: 6, fontSize: 8, fontWeight: '900' },
  recipeListCopy: { flex: 1 },
  recipeListProfile: { color: '#796E7D', fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },
  recipeListTitle: { color: ink, fontSize: 16, lineHeight: 20, fontWeight: '800', marginTop: 5 },
  recipeListNotes: { color: '#887C8B', fontSize: 10, marginTop: 7 },
  recipeListArrow: { color: '#7A6D7E', fontSize: 25 },
  recipeListFavorite: { width: 48, height: 103, alignItems: 'center', justifyContent: 'center', borderLeftWidth: 1, borderLeftColor: line },
  recipeListFavoriteText: { color: '#756979', fontSize: 22 },
  recipeListFavoriteTextActive: { color: coral },
  emptyCollection: { alignItems: 'center', padding: 30, borderRadius: 27, backgroundColor: surface, borderWidth: 1, borderColor: line },
  emptyCollectionIcon: { width: 70, height: 70, borderRadius: 35, alignItems: 'center', justifyContent: 'center', backgroundColor: '#291C2F' },
  emptyCollectionIconText: { color: coral, fontSize: 33 },
  emptyCollectionTitle: { color: ink, fontSize: 22, fontWeight: '800', marginTop: 19 },
  emptyCollectionText: { maxWidth: 330, color: muted, fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 9 },
  emptyCollectionButton: { paddingHorizontal: 18, paddingVertical: 13, borderRadius: 15, backgroundColor: coral, marginTop: 21 },
  emptyCollectionButtonText: { color: '#271416', fontSize: 13, fontWeight: '900' },
  systemCard: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 13, borderRadius: 20, backgroundColor: surface, borderWidth: 1, borderColor: line, marginTop: 28 },
  systemIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#2B2031' },
  systemIconText: { color: '#C7A6FF', fontSize: 17, fontWeight: '900' },
  systemCopy: { flex: 1 },
  systemTitle: { color: ink, fontSize: 13, fontWeight: '800' },
  systemText: { color: '#817584', fontSize: 10, marginTop: 4 },
  systemAction: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, backgroundColor: '#2D2033' },
  systemActionText: { color: '#C7A6FF', fontSize: 10, fontWeight: '900' },

  navWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 16, paddingBottom: Platform.OS === 'ios' ? 8 : 12, alignItems: 'center' },
  nav: { width: '100%', maxWidth: 520, height: 76, flexDirection: 'row', alignItems: 'center', padding: 7, borderRadius: 27, backgroundColor: '#211827', borderWidth: 1, borderColor: '#3B2C42', elevation: 18, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: .42, shadowRadius: 18 },
  navItem: { flex: 1, height: 61, borderRadius: 20, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navItemActive: { backgroundColor: '#F4E9E1' },
  navIconWrap: { minWidth: 27, minHeight: 24, alignItems: 'center', justifyContent: 'center' },
  navIcon: { color: '#8C7D91', fontSize: 19, fontWeight: '800' },
  navIconActive: { color: '#2B1C24' },
  navLabel: { color: '#8C7D91', fontSize: 9, fontWeight: '800' },
  navLabelActive: { color: '#2B1C24' },
  navCount: { position: 'absolute', top: -3, right: -8, minWidth: 16, height: 16, paddingHorizontal: 4, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: coral },
  navCountText: { color: '#2B1115', fontSize: 8, fontWeight: '900' },

  modalSafe: { flex: 1, backgroundColor: '#0D0911', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  recipeSheet: { width: '100%', maxWidth: 680, alignSelf: 'center', paddingHorizontal: 18, paddingTop: 10, paddingBottom: 44 },
  modalHeader: { minHeight: 55, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 23 },
  modalClose: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: raised, borderWidth: 1, borderColor: line },
  modalCloseText: { color: ink, fontSize: 25, lineHeight: 28 },
  recipePassport: { position: 'relative', overflow: 'hidden', padding: 20, borderRadius: 30, backgroundColor: '#F4E9E1' },
  passportAccent: { height: 7, position: 'absolute', left: 0, right: 0, top: 0 },
  passportTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  passportKicker: { color: '#66545E', fontSize: 9, fontWeight: '900', letterSpacing: 1.8 },
  passportCode: { color: '#A08D96', fontSize: 9, fontWeight: '700', letterSpacing: 1.1, marginTop: 5 },
  passportSeal: { width: 50, height: 50, borderRadius: 25, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  passportSealText: { fontSize: 24 },
  passportProfile: { fontSize: 10, fontWeight: '900', letterSpacing: 1.7, marginTop: 27 },
  passportTitle: { color: '#271B21', fontSize: 39, lineHeight: 44, fontWeight: '700', letterSpacing: -1.6, marginTop: 9 },
  passportDescription: { color: '#74626B', fontSize: 15, lineHeight: 23, marginTop: 13 },
  passportDivider: { height: 32, flexDirection: 'row', alignItems: 'center', marginHorizontal: -20, marginTop: 15 },
  passportNotchLeft: { width: 16, height: 32, borderTopRightRadius: 16, borderBottomRightRadius: 16, backgroundColor: '#0D0911' },
  passportNotchRight: { width: 16, height: 32, borderTopLeftRadius: 16, borderBottomLeftRadius: 16, backgroundColor: '#0D0911' },
  passportDash: { flex: 1, borderTopWidth: 1, borderStyle: 'dashed', borderColor: '#C6B7B7' },
  passportSectionTitle: { color: '#745F69', fontSize: 9, fontWeight: '900', letterSpacing: 1.7, marginBottom: 5 },
  passportIngredients: { gap: 1 },
  passportRow: { minHeight: 73, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#D5C8C3' },
  passportIngredientNumber: { width: 33, height: 33, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  passportIngredientNumberText: { fontSize: 12, fontWeight: '900' },
  passportIngredientName: { flex: 1, color: '#302228', fontSize: 15, lineHeight: 21, fontWeight: '700' },
  passportPercent: { flexDirection: 'row', alignItems: 'baseline' },
  passportPercentValue: { color: '#271B21', fontSize: 26, fontWeight: '900' },
  passportPercentMark: { color: '#8B7881', fontSize: 11, marginLeft: 2 },
  masterNote: { padding: 17, borderRadius: 19, backgroundColor: '#E6DAD4', marginTop: 23 },
  masterNoteLabel: { color: '#806B74', fontSize: 8, fontWeight: '900', letterSpacing: 1.5 },
  masterNoteText: { color: '#3C2D34', fontSize: 14, lineHeight: 22, marginTop: 9 },
  passportSource: { paddingTop: 19, marginTop: 19, borderTopWidth: 1, borderTopColor: '#D2C5C0' },
  passportSourceLabel: { color: '#8C7780', fontSize: 8, fontWeight: '900', letterSpacing: 1.5 },
  passportSourceTitle: { color: '#34262D', fontSize: 14, fontWeight: '800', marginTop: 7 },
  passportSourceLink: { color: '#735A66', fontSize: 11, marginTop: 5 },
  modalActions: { flexDirection: 'row', gap: 9, marginTop: 14 },
  modalSave: { minHeight: 56, paddingHorizontal: 17, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#44344B', backgroundColor: raised },
  modalSaveActive: { backgroundColor: '#F4E9E1', borderColor: '#F4E9E1' },
  modalSaveText: { color: coral, fontSize: 13, fontWeight: '900' },
  modalSaveTextActive: { color: '#2B1C24' },
  modalShare: { flex: 1, minHeight: 56, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, borderRadius: 18, backgroundColor: coral },
  modalShareText: { color: '#271416', fontSize: 14, fontWeight: '900' },
  modalShareArrow: { color: '#271416', fontSize: 20, marginLeft: 'auto' },
  modalHint: { color: '#746A78', fontSize: 11, lineHeight: 18, textAlign: 'center', marginTop: 18, paddingHorizontal: 12 },
});
