import { Platform, StatusBar, StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#141714', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  content: { padding: 24, paddingBottom: 40, width: '100%', maxWidth: 620, alignSelf: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 22 },
  logo: { fontSize: 27, fontWeight: '800', color: '#F4F5EF', letterSpacing: -1 },
  logoMark: { color: '#D5F589' },
  meta: { fontSize: 12, color: '#A7AFA3' },
  savedBadge: { minWidth: 58, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, backgroundColor: '#252B24', alignItems: 'center' },
  savedBadgeActive: { backgroundColor: '#D5F589' },
  savedBadgeText: { color: '#D5F589', fontWeight: '700' },
  savedBadgeTextActive: { color: '#202B17' },
  catalogLink: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderRadius: 16, backgroundColor: '#20271F', marginBottom: 30 },
  catalogLinkText: { fontSize: 16, fontWeight: '700', color: '#F4F5EF' },
  catalogLinkMeta: { fontSize: 13, color: '#D5F589' },
  updateBanner: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 18, borderRadius: 18, backgroundColor: '#D5F589', marginBottom: 28 },
  updateCopy: { flex: 1 },
  updateEyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.3, color: '#526239' },
  updateTitle: { fontSize: 19, fontWeight: '800', color: '#202B17', marginTop: 5 },
  updateText: { fontSize: 12, lineHeight: 18, color: '#425033', marginTop: 4 },
  updateDownload: { paddingHorizontal: 13, paddingVertical: 12, borderRadius: 13, backgroundColor: '#263B20' },
  updateDownloadText: { color: '#F4F5EF', fontSize: 12, fontWeight: '800' },
  eyebrow: { fontSize: 12, fontWeight: '700', letterSpacing: 1.6, color: '#D5F589' },
  title: { fontSize: 44, fontWeight: '700', color: '#F4F5EF', lineHeight: 49, letterSpacing: -1.5, marginTop: 15 },
  subtitle: { fontSize: 16, color: '#A7AFA3', lineHeight: 24, marginTop: 14 },
  stats: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 25, padding: 17, borderWidth: 1, borderColor: '#2D352B', borderRadius: 18 },
  statValue: { fontSize: 20, fontWeight: '800', color: '#F4F5EF', textAlign: 'center' },
  statLabel: { fontSize: 11, color: '#8F998B', marginTop: 3, textAlign: 'center' },
  statDivider: { width: 1, height: 32, backgroundColor: '#364033' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 20, marginBottom: 26 },
  chip: { paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, backgroundColor: '#252B24' },
  activeChip: { backgroundColor: '#D5F589' },
  chipText: { fontSize: 14, color: '#CDD2C8' },
  activeText: { color: '#1E2916', fontWeight: '700' },
  card: { backgroundColor: '#20271F', padding: 24, borderRadius: 25, borderWidth: 1 },
  row: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 8 },
  sourceCard: { marginTop: 20, padding: 14, borderRadius: 14, backgroundColor: '#2B3329' },
  sourceLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.4, color: '#D5F589' },
  sourceAuthor: { fontSize: 15, fontWeight: '700', color: '#F4F5EF', marginTop: 6 },
  sourceLink: { fontSize: 12, color: '#A7AFA3', marginTop: 4 },
  recipeTitle: { fontSize: 31, lineHeight: 37, fontWeight: '700', color: '#F4F5EF', marginTop: 25, letterSpacing: -.7 },
  description: { fontSize: 16, color: '#BAC3B5', lineHeight: 24, marginTop: 12 },
  bar: { height: 8, flexDirection: 'row', gap: 4, borderRadius: 10, overflow: 'hidden', marginTop: 25, marginBottom: 18 },
  ingredient: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  ingredientName: { flex: 1, fontSize: 16, color: '#E0E7D9' },
  percent: { fontSize: 17, fontWeight: '600', color: '#F4F5EF' },
  cardActions: { flexDirection: 'row', gap: 10, marginTop: 23 },
  favoriteButton: { width: 56, borderWidth: 1, borderColor: '#65725D', borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  favoriteButtonText: { color: '#D5F589', fontSize: 25 },
  outlineButton: { borderWidth: 1, borderColor: '#65725D', borderRadius: 15, padding: 16, alignItems: 'center' },
  cardPrimaryAction: { flex: 1 },
  whiteButtonText: { color: '#F4F5EF', fontSize: 16, fontWeight: '600' },
  primary: { backgroundColor: '#D5F589', borderRadius: 18, padding: 20, alignItems: 'center', marginTop: 16 },
  pressed: { opacity: .8 },
  primaryText: { fontSize: 18, fontWeight: '700', color: '#202B17' },
  hint: { fontSize: 12, color: '#A7AFA3', textAlign: 'center', marginTop: 12 },
  section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 14, marginTop: 37, marginBottom: 12 },
  sectionTitle: { fontSize: 22, fontWeight: '600', color: '#F4F5EF' },
  sectionCaption: { fontSize: 12, color: '#8F998B', marginTop: 5 },
  sectionToggle: { paddingHorizontal: 13, paddingVertical: 10, borderRadius: 18, backgroundColor: '#252B24' },
  sectionToggleText: { color: '#D5F589', fontSize: 12, fontWeight: '700' },
  listItem: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#2A3228' },
  listMain: { flex: 1, flexDirection: 'row', gap: 14, alignItems: 'center', paddingVertical: 16 },
  listCopy: { flex: 1 },
  listFavorite: { width: 46, height: 54, alignItems: 'center', justifyContent: 'center' },
  listFavoriteText: { color: '#D5F589', fontSize: 23 },
  swatch: { width: 48, height: 54, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  swatchText: { fontSize: 18, fontWeight: '700', color: '#263322' },
  listTitle: { fontSize: 17, color: '#F4F5EF', fontWeight: '600' },
  listSub: { fontSize: 13, color: '#A7AFA3', marginTop: 6, lineHeight: 19 },
  arrow: { fontSize: 23, color: '#A7AFA3' },
  emptySaved: { alignItems: 'center', padding: 28, borderRadius: 20, backgroundColor: '#20271F', marginTop: 8 },
  emptySavedIcon: { color: '#D5F589', fontSize: 35 },
  emptySavedTitle: { color: '#F4F5EF', fontSize: 19, fontWeight: '700', marginTop: 10 },
  emptySavedText: { color: '#A7AFA3', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 8 },
  versionCard: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 17, borderRadius: 17, backgroundColor: '#20271F', marginTop: 30 },
  versionCopy: { flex: 1 },
  versionTitle: { color: '#F4F5EF', fontSize: 15, fontWeight: '700' },
  versionText: { color: '#8F998B', fontSize: 12, marginTop: 4 },
  versionButton: { paddingHorizontal: 14, paddingVertical: 11, borderRadius: 13, backgroundColor: '#2F382D' },
  versionButtonText: { color: '#D5F589', fontSize: 12, fontWeight: '700' },
  footer: { fontSize: 13, lineHeight: 20, color: '#A7AFA3', marginTop: 30 },
  recipeSafe: { flex: 1, backgroundColor: '#F1F3E9', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  sheet: { padding: 26, paddingBottom: 45, maxWidth: 620, width: '100%', alignSelf: 'center' },
  sheetBrand: { fontSize: 17, fontWeight: '700', color: '#24301E' },
  close: { paddingVertical: 14, paddingHorizontal: 8 },
  closeText: { fontSize: 14, color: '#374A2D' },
  paperTopline: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  paperFavorite: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 16, backgroundColor: '#DDE5D3' },
  paperFavoriteText: { fontSize: 12, fontWeight: '700', color: '#374A2D' },
  paperEyebrow: { fontSize: 12, fontWeight: '700', letterSpacing: 1.5, color: '#526647' },
  paperTitle: { fontSize: 42, lineHeight: 48, fontWeight: '700', letterSpacing: -1, color: '#202C1A', marginTop: 20 },
  paperDescription: { fontSize: 18, lineHeight: 27, color: '#52604A', marginTop: 18 },
  paperSource: { marginTop: 24, padding: 16, borderRadius: 15, backgroundColor: '#DDE5D3' },
  paperSourceLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.3, color: '#526647' },
  paperSourceAuthor: { fontSize: 16, fontWeight: '700', color: '#24301E', marginTop: 7 },
  paperSourceLink: { fontSize: 13, color: '#526647', marginTop: 5 },
  paperIngredients: { marginVertical: 30, borderTopWidth: 1, borderColor: '#BAC5B0' },
  paperRow: { flexDirection: 'row', alignItems: 'center', gap: 18, paddingVertical: 21, borderBottomWidth: 1, borderColor: '#BAC5B0' },
  paperName: { flex: 1, fontSize: 22, color: '#24301E' },
  paperPercent: { fontSize: 28, fontWeight: '700', color: '#24301E' },
  paperNote: { fontSize: 18, lineHeight: 28, color: '#24301E', marginTop: 12 },
  paperHint: { fontSize: 14, lineHeight: 22, color: '#52604A', marginTop: 25 },
  shareButton: { backgroundColor: '#263B20', padding: 19, borderRadius: 16, alignItems: 'center', marginTop: 30 },
});
